// Qualitative research and sell-side consensus per company, retrieved 1-2 Oct 2026.
// Targets are 12-month analyst targets in US dollars; refUsd is the share price the upside figures were measured against.
module.exports = {
  US67066G1040: {
    industry: 'Semiconductors · AI accelerators',
    market: 'Sells the GPUs, networking and software that train and run most large AI models. Data centre is about 92% of revenue, so results track hyperscaler and AI-cloud capital spending.',
    position: 'Market leader with a software moat (CUDA) and full-system offering; gross margin around 75%.',
    competitors: ['AMD (Instinct GPUs)', 'Broadcom and Marvell (custom AI chips)', 'Google TPU, Amazon Trainium (in-house silicon)', 'Intel'],
    bull: 'AI capex keeps compounding into 2027, new platforms ship on time, China sales reopen and the $235bn buyback supports the share count.',
    bear: 'Hyperscalers slow spending or shift to in-house chips, margins slip from 75%, and the multiple compresses with the AI trade.',
    cons: { rating: 'Strong Buy', analysts: 61, refUsd: 230.85, avg: 327.7, low: 180, high: 515, src: { t: 'StockAnalysis consensus', u: 'https://stockanalysis.com/stocks/nvda/forecast/' } },
  },
  US8740391003: {
    industry: 'Semiconductors · Contract manufacturing (foundry)',
    market: 'Makes leading-edge chips for Nvidia, Apple, AMD, Broadcom and others; advanced packaging (CoWoS) is the bottleneck for AI accelerators. 2026 revenue growth guided above 40% in dollars.',
    position: 'Dominant share of leading-edge foundry; operating margin about 60%. Capex of $60–64bn widens the gap.',
    competitors: ['Samsung Foundry', 'Intel Foundry', 'SMIC (China)', 'GlobalFoundries and UMC (mature nodes)'],
    bull: 'AI demand keeps exceeding capacity, pricing rises on 2nm and packaging, and overseas fabs ramp without denting margins.',
    bear: 'Taiwan geopolitical shock, tariffs on chips, or an AI order pause that leaves heavy capex under-used.',
    cons: { rating: 'Strong Buy', analysts: 21, refUsd: 459.2, avg: 552.26, low: 440, high: 700, src: { t: 'FinanceFeeds: TSM targets $440–700', u: 'https://financefeeds.com/tsm-stock-bull-bear-analyst-targets-ai-chip/' } },
  },
  US02079K3059: {
    industry: 'Internet · Search, advertising and cloud',
    market: 'Search and YouTube advertising fund the business; Google Cloud (+82% in Q2) and Gemini are the growth engines. 2026 capex guided up to $205bn.',
    position: 'Largest search and video audience, own AI chips (TPU) and frontier models; Gemini app around 950 million monthly users.',
    competitors: ['Microsoft and OpenAI (AI assistants, Azure)', 'Meta (advertising)', 'Amazon (AWS cloud, retail ads)', 'Perplexity and other AI search'],
    bull: 'Cloud keeps accelerating, Gemini monetises inside Search without hurting ad revenue, and capex returns become visible.',
    bear: 'AI assistants erode search share, capex keeps rising faster than revenue, and antitrust remedies bite.',
    cons: { rating: 'Strong Buy', analysts: 54, refUsd: 338.8, avg: 429.36, low: 340, high: 515, refNote: 'reference price converted from euro', src: { t: 'Investing.com consensus', u: 'https://www.investing.com/equities/google-inc-consensus-estimates' } },
  },
  US5324571083: {
    industry: 'Pharmaceuticals · Obesity and diabetes (GLP-1)',
    market: 'Incretin drugs are the fastest-growing drug class: Mounjaro and Zepbound made $14.9bn in Q2 alone. Oral Foundayo launched in Q2; full-year revenue guided to $85–87bn.',
    position: 'Leading share of new GLP-1 prescriptions with an injectable, a pill and next-generation retatrutide (filing planned Q1 2027).',
    competitors: ['Novo Nordisk (Wegovy, oral semaglutide)', 'Amgen (MariTide)', 'Pfizer (via Metsera)', 'Roche, Viking Therapeutics'],
    bull: 'Foundayo becomes the mass-market pill, retatrutide extends the lead, and payers widen obesity coverage.',
    bear: 'US price cuts or coverage limits, safety findings, and Novo winning back share on price.',
    cons: { rating: 'Buy', analysts: null, refUsd: 1150, avg: 1392.5, low: 850, high: 1600, refNote: 'median target; reference price converted from euro', src: { t: 'Yahoo Finance: price target boost', u: 'https://finance.yahoo.com/markets/stocks/articles/eli-lilly-lly-gets-big-155107945.html' } },
  },
  US5951121038: {
    industry: 'Semiconductors · Memory (DRAM, HBM, NAND)',
    market: 'AI servers need high-bandwidth memory; prices have surged and supply is sold out. Fiscal 2026 revenue $133bn (+256%), next quarter guided to about $61.5bn.',
    position: 'One of three DRAM makers; most of 2027 HBM supply already contracted at higher prices.',
    competitors: ['SK Hynix', 'Samsung', 'CXMT (China)', 'Kioxia and SanDisk (NAND)'],
    bull: 'Memory stays tight through 2027, HBM4 share gains with Nvidia, and record margins hold longer than in past cycles.',
    bear: 'The cycle turns: rivals add capacity, Chinese supply grows and prices fall, as in the 28.7% drop in July.',
    cons: { rating: 'Strong Buy', analysts: 49, refUsd: 1065.1, avg: 1533.8, low: 1100, high: 2100, src: { t: 'Benzinga: analysts lift targets', u: 'https://www.benzinga.com/analyst-stock-ratings/analyst-color/26/10/62120688/micron-stock-erases-post-earnings-losses-analyst-price-targets' } },
  },
  US92537N1081: {
    industry: 'Industrials · Data-centre power and cooling',
    market: 'Sells power, thermal and liquid-cooling systems for data centres. Q2 organic growth 18%; full-year adjusted EPS guided to $6.65–6.75.',
    position: 'Leader in data-centre thermal management, expanding liquid-cooling services through acquisitions.',
    competitors: ['Schneider Electric', 'Eaton', 'ABB', 'nVent, Munters and Johnson Controls (cooling)'],
    bull: 'The July revenue miss proves temporary, liquid cooling scales with each GPU generation and orders stay ahead of shipments.',
    bear: 'Project delays repeat, hyperscaler concentration hurts pricing and the high beta works in reverse.',
    cons: { rating: 'Moderate Buy', analysts: 29, refUsd: 246.55, avg: 357.08, low: 260, high: 500, src: { t: 'MarketBeat consensus', u: 'https://www.marketbeat.com/stocks/NYSE/VRT/forecast/' } },
  },
  CA2926717083: {
    industry: 'Energy and materials · Uranium and rare earths',
    market: 'US uranium producer (1.7m lb in the first half) building a rare-earth separation and magnet chain; uranium spot fell 8.7% in September to about $89/lb.',
    position: 'Only US mill processing both uranium and rare earths; terbium oxide qualified by a large non-China magnet maker.',
    competitors: ['Cameco, Kazatomprom, Uranium Energy (uranium)', 'Lynas, MP Materials, Iluka (rare earths)', 'Chinese processors'],
    bull: 'Uranium contract prices rise, rare-earth sales to Western magnet makers start, and the Vacuumschmelze deal closes on good terms.',
    bear: 'Uranium keeps sliding, acquisitions strain the balance sheet and rare-earth revenue arrives late.',
    cons: { rating: 'Moderate Buy', analysts: 7, refUsd: 10.78, avg: 21.85, low: 16, high: 29.25, refNote: 'targets look stale after the September fall; reference price converted from euro', src: { t: 'MarketBeat consensus', u: 'https://www.marketbeat.com/stocks/NYSEAMERICAN/UUUU/forecast/' } },
  },
  US5533681012: {
    industry: 'Materials · Rare earths and magnets',
    market: 'Mines and processes rare earths at Mountain Pass, California, and starts commercial magnet shipments to GM in Q4 2026. Q2 revenue +89%.',
    position: 'Largest integrated rare-earth producer in the West, central to US efforts to cut reliance on China.',
    competitors: ['China Northern Rare Earth', 'Lynas Rare Earths', 'Iluka, USA Rare Earth, Energy Fuels', 'Chinese magnet makers'],
    bull: 'Magnet output ramps on schedule, China export curbs keep Western prices high and new customers sign.',
    bear: 'China eases curbs and prices fall, the magnet ramp slips, or the Shenghe ownership issue escalates.',
    cons: { rating: 'Strong Buy', analysts: 19, refUsd: 45.72, avg: 74.29, low: 57, high: 100, src: { t: 'StockAnalysis consensus', u: 'https://stockanalysis.com/stocks/mp/forecast/' } },
  },
};
